framework:
  secret: %secret%
  translator: { fallbacks: ["%locale%"] }

  router:
    resource: "%kernel.root_dir%/config/routing.yml"

  templating:
    engines: ['twig']

  default_locale: %locale%

twig:
  strict_variables: true